[package]
name = "egyan"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["blocking", "native-tls"], default-features = false }
scraper = "0.19.0"

[profile.dev.package."*"]
opt-level = 3
